[package]
name = "rust"
version = "1.0.0"
edition = "2024"
license = "MIT"

[dependencies]
godot = { version = "0.3.5", features = ["register-docs"] }

[lib]
crate-type = ["cdylib"] # Compile this crate to a dynamic C library.
